pytest --no-cov --nbmake `
   ".\other\make_banner.ipynb" `
   ".\other\hello_world.ipynb" `
   ".\examples\how_to_customize_regions_in_2d_mesh.ipynb" `
   ".\how_to_generate_a_triangle_mesh_from_a_2d_image" `
   ".\examples\how_to_do_3d_multi-domain_meshing_using_simulated_data.ipynb" `
   ".\examples\how_to_generate_a_tetrahedral_mesh_from_3d_cells_image.ipynb" `
   ".\examples\how_to_pad_a_2d_mesh.ipynb" `
   ".\examples\how_to_pad_a_3d_mesh.ipynb" `
   ".\nanopores\how_to_calculate_cell_quality_metrics.ipynb" `
   ".\nanopores\how_to_examine_nanopore_properties_using_regionprops.ipynb" `
   ".\nanopores\how_to_generate_a_tetrahedral_mesh_from_3d_nanopores data.ipynb" `
   ".\nanopores\how_to_generate_a_triangle_mesh_from_a_2d_nanopore_data.ipynb" `
   ".\nanopores\how_to_process_a_large_data_file.ipynb" `
   ".\nanopores\how_to_segment_image_data_using_local_thresholds.ipynb" `
   ".\nanopores\how_to_select_a_region_of_interest_from_an_image.ipynb" `
   ".\nanopores\how_to_select_a_region_of_interest_using_ffts.ipynb" `
