import sys
from pathlib import Path

root = Path(__file__).absolute().parent.parent
sys.path.insert(0, str(root))

DOCSDIR = '.'
BUILDDIR = '_build'
TEMPLATESDIR = '_templates'
STATICDIR = '_static'
SOURCEDIR = '../nanomesh'


# Include banner as static image
def copy_banner_to_static(app):
    import shutil
    src = Path('.').absolute().parent / 'notebooks' / 'other' / 'banner.png'
    target = Path(STATICDIR)
    target.mkdir(exist_ok=True)
    shutil.copy2(src, target)


# https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events
# https://github.com/readthedocs/readthedocs.org/issues/2276
def setup(app):
    app.connect('builder-inited', copy_banner_to_static)


extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'nbsphinx',
    'nbsphinx_link',
    'autodocsumm',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'nanomesh'
copyright = u'2020, '
author = u'Nicolas Renaud'

# The short X.Y version.
version = release = '0.7.0'

# The language for content autogenerated by Sphinx.
language = 'english'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = [BUILDDIR, 'Thumbs.db', '.DS_Store']

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = [STATICDIR]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Use autoapi.extension to run sphinx-apidoc
autoapi_dirs = [SOURCEDIR]

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

autodoc_default_options = {
    'autosummary': True,
}

nbsphinx_allow_errors = True
nbsphinx_execute = 'never'

autodoc_mock_imports = [
    'ipywidgets',
    'itkwidgets',
    'pyvista',
]

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'pyvista': ('https://docs.pyvista.org', None),
    'scipy': ('https://docs.scipy.org/doc/scipy/', None),
    'scikit-image': ('https://scikit-image.org/docs/stable/', None),
    'scikit-learn': ('https://scikit-learn.org/stable/', None),
    'matplotlib': ('https://matplotlib.org/stable/', None),
}

# Ensure env.metadata[env.docname]['nbsphinx-link-target']
# points relative to repo root:
nbsphinx_link_target_root = root

nbsphinx_prolog = """
{% if env.metadata[env.docname]['nbsphinx-link-target'] %}
    {% set docpath = env.metadata[env.docname]['nbsphinx-link-target'] %}
{% else %}
    {% set docpath = env.doc2path(env.docname, base=None) %}
{% endif %}

.. nbinfo::
    This page was generated from: `{{ docpath }} <https://github.com/hpgem/nanomesh/tree/{{ env.config.release|e }}/{{ docpath }}>`__

----
"""

nbsphinx_epilog = """
----

Generated by nbsphinx_ from a Jupyter_ notebook.

.. _nbsphinx: http://nbsphinx.readthedocs.io/
.. _Jupyter: https://jupyter.org/
"""
