name: Tests

on:
  push:
    branches:
      - master
      - update-test-workflow
  pull_request:
    branches:
      - master
      - update-test-workflow

jobs:
  test:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('constraints.txt') }}

      - name: Python info
        run: |
          which python
          python --version

      - name: Install dependencies
        run: |
          python -m pip install -c constraints.txt -e .[develop]

      # Linux / Mac
      - name: Install tetgen linux/mac
        if: runner.os != 'Windows'
        run: |
          wget -O tetgen.zip https://github.com/hpgem/tetgen/releases/download/1.6.0/tetgen-${{ runner.os }}.zip
          unzip tetgen.zip
          mv tetgen /usr/local/bin/
          which tetgen

      # Windows
      - name: Install tetgen windows
        if: runner.os == 'Windows'
        run: |
          $env:path.Split(";")
          Invoke-WebRequest -Uri "https://github.com/hpgem/tetgen/releases/download/1.6.0/tetgen-${{ runner.os }}.zip" -OutFile "tetgen.zip"
          Expand-Archive tetgen.zip -DestinationPath .
          mv tetgen.exe C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps
          gcm tetgen.exe

      - name: Test with pytest
        run: python -m pytest --disable-warnings
