name: Test on Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.8']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('constraints.txt') }}

      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version

      - name: Install Linux dependencies
        shell: bash -l {0}
        run: sudo apt-get install libcgal-dev libeigen3-dev

      - name: Install dependencies
        shell: bash -l {0}
        # make sure to do eager upgrade to avoice cache going stale
        run: |
          python -m pip install  -c constraints.txt -e .[develop,with_pygalmesh]

      - name: Test with pytest
        shell: bash -l {0}
        run: python -m pytest --disable-warnings
