name: Test on MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest']
        python-version: ['3.8', '3.9']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}

      - name: Python info
        shell: bash
        run: |
          which python
          python --version

      # Disabled -> https://github.com/hpgem/nanomesh/issues/35
      # - name: Install MacOS dependencies
      #   run: brew install cgal eigen

      - name: Install dependencies
        shell: bash
        # make sure to do eager upgrade to avoice cache going stale
        run: |
          python -m pip install --upgrade --upgrade-strategy eager -e .[develop]

      - name: Test with pytest
        shell: bash
        run: python -m pytest --disable-warnings
