name: Update dependencies

on:
  # every month
  schedule:
    - cron: "30 6 5 * *"
  # on demand
  workflow_dispatch:

jobs:
  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - run: pip install pre-commit
      - run: pre-commit autoupdate
      - run: pre-commit run --all-files || true

      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "Update pre-commit hooks"
          body: Update pre-commit hooks to latest version and run on all files.


  dependencies-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Update constraints.txt
        shell: pwsh
        run: |
          pip install -e .[develop]
          pip freeze --exclude nanomesh > constraints.txt

      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-deps
          title: Update dependencies
          commit-message: "Update constraints.txt (windows)"
          body: Update dependencies in constraints.txt


  dependencies-linux:
    needs: dependencies-win

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: update-deps

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Update constraints.txt
        run: |
          pip install -e .[develop] -c constraints.txt
          pip freeze --exclude nanomesh >> constraints.txt
          sort --ignore-case constraints.txt | uniq > constraints_tmp.txt
          mv constraints_tmp.txt constraints.txt

      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add constraints.txt
          git commit -m "Update constraints.txt (linux)"
          git push
